services:
  - type: web
    name: star-wars-films-api
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn star_wars_films.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com,127.0.0.1,localhost"
      - key: DATABASE_URL
        fromDatabase:
          name: star-wars-db
          property: connectionString

databases:
  - name: star-wars-db
    plan: free
